-- -- Active: 1726587554496@@127.0.0.1@3306@springbootblogdb
SET FOREIGN_KEY_CHECKS = 0;
-- DROP TABLE `comment`;
-- DROP TABLE `tag`;
-- DROP TABLE `role`;
-- DROP TABLE `category`;
-- DROP TABLE `user`;
-- DROP TABLE `user_role`;
-- DROP TABLE `post`;
-- DROP TABLE `post_tag`;
-- DROP TABLE `tag_id`;
SET FOREIGN_KEY_CHECKS = 1;